version: '3.8'
services:
  vcare-api:
    container_name: 'vcare-api'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '4021:8080'
    volumes:
      - '/home/fileStorage/images:/home/votey/media'