server:
  port: 8080

spring:
  application:
    name: "Vcare"

  datasource:
    url: jdbc:postgresql://34.142.239.81:4030/product-db
    username: postgres
    password: lyhou123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
